[package]
name = "couleur-rs"
version = "0.1.0"
description = "parse, print, manipulate and apply contrast to RGB colors"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2024"
autoexamples = false
autobenches = false
autotests = false

homepage = "https://crates.io/crates/couleur-rs"
documentation = "https://docs.rs/couleur-rs"
repository = "https://github.com/gabrielfalcao/couleur-rs"

keywords = ["color", "ansi", "unix", "system"]
authors = ["Gabriel DeMoura <gabrielteratos@gmail.com>"]
categories = ["command-line-interface"]
# # default-run = "couleur"
# default-run = "hex-to-bin"
# # default-run = "terminal-info"
default-run = "contrast"

# categories = [] # https://crates.io/category_slugs

[features]
tracing = [
    "dep:tracing",
    "dep:tracing-subscriber",
    "dep:tracing-appender",
]
logging = [
    "dep:log",
    "dep:fern",
    "dep:chrono",
]
dirs = ["dep:dirs"]

[dependencies]
# bon = "3.9.3"
clap = { version = "4.6.1", features = ["derive", "env", "string", "unicode", "wrap_help"] }
heck = "0.5.0"
hex = "0.4.3"
iocore = "3.1.0"
regex = "1.12.4"
serde = { version = "1.0.228", features = ["derive"] }
supports-color = "3.0.2"
terminal-colorsaurus = "1.0.3"
thiserror = "2.0.18"
serde_json = "1.0.150"
serde_yaml = "0.9.34"
winnow = "1.0.4"
log = { version = "0.4.33", features = ["serde", "kv", "kv_serde"], optional = true }
fern = { version = "0.7.1", features = ["chrono", "colored"], optional = true }
chrono = { version = "0.4.45", features = ["serde"], optional = true }
is-terminal = "0.4.17"
tracing = { version = "0.1.44", features = ["log", "log-always"], optional = true }
tracing-subscriber = { version = "0.3.23", features = ["serde", "serde_json", "json", "chrono", "env-filter"], optional = true }
tracing-appender = { version = "0.2.5", optional = true }
dirs = { version = "6.0.0", optional = true }


# cargo add --optional tracing tracing-subscriber tracing-appender


[package.metadata]
targets = [
    # "aarch64-apple-darwin",
    # "x86_64-unknown-linux-gnu",
    # "aarch64-unknown-linux-gnu",
]

[lib]
name = "couleur_rs"
path = "src/lib.rs"

bench = false
doctest = false
test = true


[[bin]]
name = "couleur"
path = "src/bin/couleur.rs"
bench = false
doc = false
test = false

[[bin]]
name = "hex-to-bin"
path = "src/bin/hex-to-bin.rs"
bench = false
doc = false
test = false

[[bin]]
name = "terminal-info"
path = "src/bin/terminal-info.rs"
bench = false
doc = false
test = false

[[bin]]
name = "contrast"
path = "src/bin/contrast.rs"
bench = false
doc = false
test = false

# [[test]]
# name = "test_terminal"
# path = "./tests/test_terminal.rs"


# [[test]]
# name = "test_colorizer"
# path = "./tests/test_colorizer.rs"

# [[test]]
# name = "test_float"
# path = "./tests/test_float.rs"

[[test]]
name = "test_templating"
path = "./tests/test_templating.rs"
# #
# # # [[test]]
# # # name = "test_rgb_color"
# # # path = "./tests/test_rgb_color.rs"
# #
# # # [[test]]
# # # name = "test_rgb_value"
# # # path = "./tests/test_rgb_value.rs"
# #
# # # [[test]]
# # # name = "test_rgb_value_ops"
# # # path = "./tests/test_rgb_value_ops.rs"


[dev-dependencies]
k9 = "0.12.0"
pretty_assertions = "1.4.1"

[profile.release] # https://github.com/johnthagen/min-sized-rust
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size. https://doc.rust-lang.org/cargo/reference/profiles.html#opt-level
lto = true
panic = "abort"
codegen-units = 1


# https://github.com/johnthagen/min-sized-rust?tab=readme-ov-file#remove-fmtdebug
