// examples:
// {color:#FB6B1D,layer:bg}
// {color:terminal_foreground,layer:bg}
// {color:resurrect-64:cold_green_medium,layer:bg}
text                                             = ${ SOI ~ token* ~ EOI}

rgb_hex                                          = @{ ASCII_HEX_DIGIT{6} }

color_rgb_hex                                    = _{ "#"? ~ rgb_hex }
color_rgb                                        = @{ ("color:" ~ color_rgb_hex) }

reset                                            = @{ "reset" }
color_name                                       = @{ ASCII_ALPHANUMERIC+ ~ ("_"+ ~ ASCII_ALPHANUMERIC+)* }

color_from_palette                               = ${ ("color:" ~ palette_name ~ ":" ~ color_name) }
color_named                                      = ${ ("color:" ~ color_name) }
color                                            = ${ color_rgb | color_from_palette | color_named }

layer_bg                                         = ${ (^"layer:bg" | ^"layer:background") }
layer_fg                                         = ${ (^"layer:fg" | ^"layer:foreground") }
layer                                            = ${ layer_bg | layer_fg }

contrast_none                                    = @{ (^"none") }
contrast_read                                    = @{ (^"read") }
contrast_high_bit                                = @{ (^"high_bit") }
contrast_harmonic                                = @{ (^"harmonic") }
contrast_web                                     = @{ (^"web") }

contrast                                         = ${ "contrast:" ~ (contrast_none | contrast_read | contrast_high_bit | contrast_harmonic | contrast_web) }
inner                                            = _{ color | layer | reset | contrast }
replacement                                      = ${ "{" ~ inner ~ ("," ~ inner)*  ~ "}"}
unhandled                                        = ${ (!(replacement)) ~ (WHITESPACE | ASCII_ALPHANUMERIC | ANY)+ }

token                                            = _{ replacement | unhandled }
WHITESPACE                                       = _{ " " | "\t" | "\n" }
